# config/_default/languages.en.toml
title = "Angiolillo Paolo"

[author]
name = "Angiolillo Paolo"
image = "profile.jpg"
headline = "DevOps Engineer"


links = [
  { twitter = "https://twitter.com/AngiolilloPaolo" },
  { github = "https://github.com/PaoloAngiolillo" },
  { linkedin = "https://www.linkedin.com/in/angiolillopaolo/" }
]
